'use client';

/**
 * Barrel file — re-exports every hook from the domain-specific modules.
 *
 * Consumers can keep importing from '@/hooks/useQueryHooks' with zero changes.
 * For new code, prefer importing directly from the domain file
 * (e.g. '@/hooks/useAdminHooks') to reduce bundle coupling.
 */

// ── Query Keys (shared across all modules) ──
export { queryKeys } from './queryKeys';

// ── Admin / Dashboard / Devices / Maintenance ──
export {
    useDashboardStats,
    useAdminUploads,
    useAdminUploadStats,
    useAdminReports,
    useAdminReport,
    useAllUsers,
    useCustomers,
    useDeleteUser,
    useUpdateUserInfo,
    useSendEmailToUser,
    useAdminChangePassword,
    usePermissionLevels,
    usePermissionModules,
    useCreatePermissionLevel,
    useUpdatePermissionLevel,
    useDeletePermissionLevel,
    useAdminCalendarEvents,
    useCreateCalendarEvent,
    useUpdateCalendarEvent,
    useDeleteCalendarEvent,
    useAdminProjects,
    useProjectHealth,
    useCreateProject,
    useDevices,
    useDevice,
    useCreateDevice,
    useUpdateDevice,
    useDeleteDevice,
    useAssignDeviceToTeamLeader,
    useBulkUploadAction,
    useUpdateReport,
    useMaintenanceOverview,
    useRefreshMaintenanceSystems,
    useDismissMaintenanceAlert,
    useAdminAnalytics,
    useAIModelConfigs,
    useCreateAIModelConfig,
    useUpdateAIModelConfig,
    useActivateAIModelConfig,
    useRollbackAIModelConfig,
    useCompareAIModelConfigs,
    useStorageConfig,
    useStorageSummary,
    useStorageUsage,
    useUpdateStorageConfig,
    useTestStorageConfig,
    useStartMigration,
    useCancelMigration,
    useMigrationStatus,
    useMigrationList,
    useBackupLogs,
} from './useAdminHooks';

// ── Operator ──
export {
    useOperatorDashboardStats,
    useOperatorTasks,
    useOperatorReports,
    useOperatorOverview,
    useStartRecording,
    useStopRecording,
    useOperatorTodayEvents,
    useOperatorAssignedProjects,
    useOperatorCalendarEvents,
    useOperatorCalendarStats,
    useCreateOperatorEvent,
    useUpdateOperatorEventStatus,
    useDeleteOperatorEvent,
    useOperatorProjects,
    useOperatorProject,
    useOperatorDevices,
    useReportDeviceStatus,
    useOperatorUploads,
    useStartOperationsRecording,
    useStopOperationsRecording,
    useCreateOperatorReport,
    useOperatorAllProjects,
    useOperatorLogs,
    useUpdateOperatorProfile,
    useChangeOperatorPassword,
    useSaveOperatorSettings,
    useOperatorNotificationPreferences,
    useUpdateOperatorNotificationPreferences,
    useOperatorChecklists,
    useCreateChecklist,
    useToggleChecklistItem,
    useDeleteChecklist,
    useOperatorRouteSites,
    useCompleteRouteSite,
    useOperatorIncidents,
    useCreateIncident,
    useUpdateIncident,
    useOperatorTimeEntries,
    useOperatorTimeSummary,
    useCreateTimeEntry,
    useDeleteTimeEntry,
    useOperatorCachedItems,
    useOperatorPendingSyncs,
    useOperatorOfflineStats,
    useToggleCache,
    useSyncAll,
} from './useOperatorHooks';

// ── QC Technician ──
export {
    useQCDashboardStats,
    useQCAssignments,
    useQCAssignment,
    useProject,
    useProjectVideos,
    useProjectDetections,
    useDetection,
    useDetectionComments,
    useReviewDetection,
    useBulkReviewDetections,
    useBulkUndoReview,
    useCreateManualDetection,
    useCompleteQCAssignment,
    useStartQCSession,
    useEndQCSession,
    useAddDetectionComment,
    useQCCertifications,
    useCreateCertification,
    useQCReports,
    useQCReportByProject,
    useQCUploads,
    usePacpDefects,
    usePacpCategories,
    useCreatePacpDefect,
    useUpdatePacpDefect,
    useDeletePacpDefect,
    useTrainingModules,
    useTrainingModule,
    useSubmitTrainingAttempt,
    useTrainingAttempts,
    useTrainingStats,
    useCreateTrainingModule,
    useUpdateTrainingModule,
    useDeleteTrainingModule,
    useTeamTrainingProgress,
    useTrainingAssignments,
    useAllTrainingAssignments,
    useAssignTrainingModules,
    useTrainingAnalytics,
    useTrainingAssignmentsOverview,
    useUserCertificates,
    useRemindTrainingAssignment,
    useOnboarding,
    useAllOnboarding,
    useCompleteOnboardingStep,
    useReviewTemplates,
    useCreateReviewTemplate,
    useUpdateReviewTemplate,
    useDeleteReviewTemplate,
    useToggleTemplateFavorite,
    useQCReviewStats,
} from './useQCHooks';

// ── Customer ──
export {
    useCustomerProjects,
    useCustomerProject,
    useCustomerObservations,
    useCustomerSnapshots,
    useCustomerDetections,
    useCustomerReports,
    useCustomerReport,
    useCustomerNotifications,
    useCustomerNotificationPreferences,
    useMarkCustomerNotificationRead,
    useMarkAllCustomerNotificationsRead,
    useDeleteCustomerNotification,
    useUpdateCustomerNotificationPreferences,
    useSubmitCustomerSupportTicket,
    useDownloadCustomerReport,
    useCustomerTracker,
    useCustomerDocuments,
    useTrackDocumentDownload,
    useCustomerAppointments,
    useAvailableSlots,
    useCreateAppointment,
    useUpdateAppointment,
    useDeleteAppointment,
    useReportAnnotations,
    useCreateAnnotation,
    useWidgetPreferences,
    useUpdateWidgetPreferences,
    useWidgetData,
    useCustomerComplaints,
    useCreateCustomerComplaint,
    useSurveyInvite,
    usePendingSurveys,
    useRespondToSurvey,
} from './useCustomerHooks';

// ── Shared / Cross-role ──
export {
    // Notes
    useNotes,
    useNote,
    useNotesStats,
    useCreateNote,
    useUpdateNote,
    useDeleteNote,
    // Shared project detail
    useProjectObservations,
    useProjectSnapshots,
    useProjectMetadata,
    usePacpCodes,
    // User inbox
    useUserInbox,
    useUserUnreadCount,
    // User (Team Lead)
    useUserDashboard,
    useUserProjects,
    useUserProject,
    useUserTeamMembers,
    useUserTeamMemberDetail,
    useUserTeamMemberDashboard,
    useUserDevices,
    useUserEvents,
    useUserNotificationPreferences,
    useUserReports,
    useUserTeamAnalyticsMetrics,
    useRequestDeleteProject,
    useApproveDeleteProject,
    useRejectDeleteProject,
    useDeleteUserProject,
    useCreateObservation,
    useCreateUserSnapshot,
    useUpdateDeviceAssignment,
    useCreateEvent,
    useUpdateEvent,
    useDeleteEvent,
    useUpdateUserProfile,
    useChangeUserPassword,
    useSaveUserSettings,
    useUpdateUserNotificationPreferences,
    // Support / Customer-Rep
    useSupportAllTickets,
    useSupportGlobalStats,
    useSupportTicket,
    useSupportAssignedTickets,
    useSupportTeam,
    useManagedTeam,
    useSupportCustomerStats,
    useCreateSupportTicket,
    useUpdateSupportTicket,
    useAddTicketResponse,
    useDeleteSupportTicket,
    useAddInternalNote,
    useSupportTags,
    useSupportCustomerHistory,
    useRequestTicketDeletion,
    useReviewTicketDeletion,
    usePendingDeletionRequests,
    // Canned Responses
    useCannedResponses,
    useCannedResponseSuggestions,
    useCreateCannedResponse,
    useUpdateCannedResponse,
    useDeleteCannedResponse,
    // Complaints
    useComplaintsAll,
    useComplaintStats,
    useComplaint,
    useComplaintsAssigned,
    useCreateComplaint,
    useUpdateComplaint,
    useDeleteComplaint,
    useAddComplaintNote,
    useCreateTicketFromComplaint,
    // Messages
    useMessagesInbox,
    useMessagesSent,
    useMessagesThread,
    useMessagesUnreadCount,
    useMessagesContacts,
    useSendMessage,
    useToggleMessageStar,
    useMarkMessageRead,
    useArchiveMessage,
    useDeleteMessage,
    useMarkAllMessagesRead,
    // Cache utilities
    useQueryUtilities,
    // Knowledge Base
    useKBArticles,
    useKBCategories,
    useCreateKBArticle,
    useUpdateKBArticle,
    useDeleteKBArticle,
    // Surveys
    useSurveyResponses,
    useSurveyStats,
    useSubmitSurvey,
    // Canned Workflows
    useCannedWorkflows,
    useCreateCannedWorkflow,
    useUpdateCannedWorkflow,
    useDeleteCannedWorkflow,
    useToggleCannedWorkflow,
    useDuplicateCannedWorkflow,
    // Survey Invites (admin)
    useSurveyInvites,
    useSendSurveys,
    // Escalation Rules
    useEscalationRules,
    useCreateEscalationRule,
    useUpdateEscalationRule,
    useDeleteEscalationRule,
    useToggleEscalationRule,
    // User new modules
    useUserWeekSchedule,
    useCreateAssignment,
    useDeleteAssignment,
    useUserBudgets,
    useUserBudget,
    useCreateBudget,
    useAddExpense,
    useUserConversations,
    useUserMessages,
    useSendClientMessage,
    useMarkConversationRead,
    useUserTemplates,
    useCreateTemplate,
    useUpdateTemplate,
    useToggleTemplateStar,
    useDuplicateTemplate,
    useDeleteTemplate,
    useUseTemplate,
    useUserTeamMetrics,
    useUserMemberMetrics,
    useUserTeamSummary,
    useCreatePerformanceMetrics,
    // Overtime
    useUserOvertimeRequests,
    useUserOvertimeSummary,
    useRequestOvertime,
    useWithdrawOvertimeRequest,
    useAdminOvertimeRequests,
    useAdminOvertimeSummary,
    useApproveOvertimeRequest,
    useRejectOvertimeRequest,
    useOvertimeApprovalQueue,
    // Rep Activity
    useRepActivity,
} from './useSharedHooks';

// ── Default export (preserves backward compat for `import hooks from ...`) ──
// Re-import everything so we can bundle it into the default object.
import { queryKeys } from './queryKeys';
import {
    useDashboardStats, useAdminUploads, useAdminUploadStats, useAdminReports, useAdminReport,
    useAllUsers, useCustomers, useDeleteUser, useUpdateUserInfo, useSendEmailToUser, useAdminChangePassword,
    usePermissionLevels, usePermissionModules,
    useCreatePermissionLevel, useUpdatePermissionLevel, useDeletePermissionLevel,
    useAdminCalendarEvents, useCreateCalendarEvent, useUpdateCalendarEvent, useDeleteCalendarEvent,
    useAdminProjects, useProjectHealth, useCreateProject, useDevices, useDevice, useCreateDevice, useUpdateDevice,
    useDeleteDevice, useAssignDeviceToTeamLeader, useBulkUploadAction, useUpdateReport,
    useMaintenanceOverview, useRefreshMaintenanceSystems, useDismissMaintenanceAlert, useAdminAnalytics,
} from './useAdminHooks';
import {
    useOperatorDashboardStats, useOperatorTasks, useOperatorReports, useOperatorOverview,
    useStartRecording, useStopRecording, useOperatorTodayEvents, useOperatorAssignedProjects,
    useOperatorCalendarEvents, useOperatorCalendarStats, useCreateOperatorEvent,
    useUpdateOperatorEventStatus, useDeleteOperatorEvent, useOperatorProjects, useOperatorProject,
    useOperatorDevices, useReportDeviceStatus, useOperatorUploads, useStartOperationsRecording,
    useStopOperationsRecording, useCreateOperatorReport, useOperatorAllProjects, useOperatorLogs,
    useUpdateOperatorProfile, useChangeOperatorPassword, useSaveOperatorSettings,
    useOperatorNotificationPreferences, useUpdateOperatorNotificationPreferences,
    useOperatorChecklists, useCreateChecklist, useToggleChecklistItem, useDeleteChecklist,
    useOperatorRouteSites, useCompleteRouteSite, useOperatorIncidents, useCreateIncident,
    useUpdateIncident, useOperatorTimeEntries, useOperatorTimeSummary, useCreateTimeEntry,
    useDeleteTimeEntry, useOperatorCachedItems, useOperatorPendingSyncs, useOperatorOfflineStats,
    useToggleCache, useSyncAll,
} from './useOperatorHooks';
import {
    useQCDashboardStats, useQCAssignments, useQCAssignment, useProject, useProjectVideos,
    useProjectDetections, useDetection, useDetectionComments, useReviewDetection,
    useBulkReviewDetections, useBulkUndoReview,
    useCreateManualDetection, useCompleteQCAssignment, useStartQCSession, useEndQCSession,
    useAddDetectionComment, useQCCertifications, useCreateCertification, useQCReports,
    useQCReportByProject, useQCUploads, usePacpDefects, usePacpCategories, useCreatePacpDefect,
    useUpdatePacpDefect, useDeletePacpDefect, useTrainingModules, useTrainingModule,
    useSubmitTrainingAttempt, useTrainingAttempts, useTrainingStats, useCreateTrainingModule,
    useUpdateTrainingModule, useDeleteTrainingModule, useTeamTrainingProgress,
    useTrainingAssignments, useAllTrainingAssignments, useAssignTrainingModules,
    useTrainingAnalytics, useTrainingAssignmentsOverview, useUserCertificates, useRemindTrainingAssignment,
    useOnboarding,
    useAllOnboarding, useCompleteOnboardingStep, useReviewTemplates, useCreateReviewTemplate,
    useUpdateReviewTemplate, useDeleteReviewTemplate, useToggleTemplateFavorite, useQCReviewStats,
} from './useQCHooks';
import {
    useCustomerProjects, useCustomerProject, useCustomerObservations, useCustomerSnapshots,
    useCustomerDetections, useCustomerReports, useCustomerReport, useCustomerNotifications,
    useCustomerNotificationPreferences, useMarkCustomerNotificationRead,
    useMarkAllCustomerNotificationsRead, useDeleteCustomerNotification,
    useUpdateCustomerNotificationPreferences, useSubmitCustomerSupportTicket,
    useDownloadCustomerReport, useCustomerTracker, useCustomerDocuments, useTrackDocumentDownload,
    useCustomerAppointments, useAvailableSlots, useCreateAppointment, useUpdateAppointment,
    useDeleteAppointment, useReportAnnotations, useCreateAnnotation, useWidgetPreferences,
    useUpdateWidgetPreferences, useWidgetData, useCustomerComplaints, useCreateCustomerComplaint,
    useSurveyInvite, usePendingSurveys, useRespondToSurvey,
} from './useCustomerHooks';
import {
    useNotes, useNote, useNotesStats, useCreateNote, useUpdateNote, useDeleteNote,
    useProjectObservations, useProjectSnapshots, useProjectMetadata, usePacpCodes,
    useUserInbox, useUserUnreadCount, useUserDashboard, useUserProjects, useUserProject,
    useUserTeamMembers, useUserTeamMemberDetail, useUserTeamMemberDashboard, useUserDevices,
    useUserEvents, useUserNotificationPreferences, useUserReports, useUserTeamAnalyticsMetrics, useRequestDeleteProject,
    useApproveDeleteProject, useRejectDeleteProject, useDeleteUserProject, useCreateObservation,
    useCreateUserSnapshot, useUpdateDeviceAssignment, useCreateEvent, useUpdateEvent, useDeleteEvent,
    useUpdateUserProfile, useChangeUserPassword, useSaveUserSettings,
    useUpdateUserNotificationPreferences, useSupportAllTickets, useSupportGlobalStats,
    useSupportTicket, useSupportAssignedTickets, useSupportTeam, useManagedTeam,
    useSupportCustomerStats, useCreateSupportTicket, useUpdateSupportTicket, useAddTicketResponse,
    useDeleteSupportTicket, useAddInternalNote, useSupportTags, useSupportCustomerHistory,
    useRequestTicketDeletion, useReviewTicketDeletion, usePendingDeletionRequests,
    useCannedResponses, useCreateCannedResponse, useUpdateCannedResponse, useDeleteCannedResponse,
    useComplaintsAll, useComplaintStats, useComplaint, useComplaintsAssigned, useCreateComplaint,
    useUpdateComplaint, useDeleteComplaint, useAddComplaintNote, useCreateTicketFromComplaint,
    useMessagesInbox, useMessagesSent, useMessagesThread, useMessagesUnreadCount,
    useMessagesContacts, useSendMessage, useToggleMessageStar, useMarkMessageRead,
    useArchiveMessage, useDeleteMessage, useMarkAllMessagesRead, useQueryUtilities,
    useKBArticles, useKBCategories, useCreateKBArticle, useUpdateKBArticle, useDeleteKBArticle,
    useSurveyResponses, useSurveyStats, useSubmitSurvey, useCannedWorkflows, useCreateCannedWorkflow,
    useUpdateCannedWorkflow, useDeleteCannedWorkflow, useToggleCannedWorkflow,
    useDuplicateCannedWorkflow, useSurveyInvites, useSendSurveys, useEscalationRules,
    useCreateEscalationRule, useUpdateEscalationRule, useDeleteEscalationRule,
    useToggleEscalationRule, useUserWeekSchedule, useCreateAssignment, useDeleteAssignment,
    useUserBudgets, useUserBudget, useCreateBudget, useAddExpense, useUserConversations,
    useUserMessages, useSendClientMessage, useMarkConversationRead, useUserTemplates,
    useCreateTemplate, useUpdateTemplate, useToggleTemplateStar, useDuplicateTemplate,
    useDeleteTemplate, useUseTemplate, useUserTeamMetrics, useUserMemberMetrics,
    useUserTeamSummary, useCreatePerformanceMetrics,
    useUserOvertimeRequests, useUserOvertimeSummary, useRequestOvertime,
    useWithdrawOvertimeRequest, useAdminOvertimeRequests, useAdminOvertimeSummary,
    useApproveOvertimeRequest, useRejectOvertimeRequest, useOvertimeApprovalQueue,
    useRepActivity,
} from './useSharedHooks';

export default {
    useDashboardStats,
    useQCDashboardStats,
    useQCAssignments,
    useQCAssignment,
    useProject,
    useProjectVideos,
    useProjectDetections,
    useDetection,
    useCreateManualDetection,
    useCompleteQCAssignment,
    useDetectionComments,
    useReviewDetection,
    useStartQCSession,
    useEndQCSession,
    useAddDetectionComment,
    useQCCertifications,
    useCreateCertification,
    useQCReports,
    useQCReportByProject,
    useNotes,
    useNote,
    useNotesStats,
    useCreateNote,
    useUpdateNote,
    useDeleteNote,
    useDevices,
    useDevice,
    useCreateDevice,
    useUpdateDevice,
    useDeleteDevice,
    useAssignDeviceToTeamLeader,
    useQueryUtilities,
    // Operator hooks (extended)
    useOperatorTodayEvents,
    useOperatorAssignedProjects,
    useOperatorCalendarEvents,
    useOperatorCalendarStats,
    useCreateOperatorEvent,
    useUpdateOperatorEventStatus,
    useDeleteOperatorEvent,
    useOperatorProjects,
    useOperatorProject,
    useOperatorDevices,
    useReportDeviceStatus,
    useOperatorUploads,
    useStartOperationsRecording,
    useStopOperationsRecording,
    useCreateOperatorReport,
    useOperatorAllProjects,
    useOperatorLogs,
    useUpdateOperatorProfile,
    useChangeOperatorPassword,
    useSaveOperatorSettings,
    useOperatorNotificationPreferences,
    useUpdateOperatorNotificationPreferences,
    // Maintenance hooks
    useMaintenanceOverview,
    useRefreshMaintenanceSystems,
    useDismissMaintenanceAlert,
    // Customer hooks
    useCustomerProjects,
    useCustomerProject,
    useCustomerObservations,
    useCustomerSnapshots,
    useCustomerDetections,
    useCustomerReports,
    useCustomerReport,
    useCustomerNotifications,
    useCustomerNotificationPreferences,
    useMarkCustomerNotificationRead,
    useMarkAllCustomerNotificationsRead,
    useDeleteCustomerNotification,
    useUpdateCustomerNotificationPreferences,
    useSubmitCustomerSupportTicket,
    useDownloadCustomerReport,
    // Customer new module hooks
    useCustomerTracker,
    useCustomerDocuments,
    useTrackDocumentDownload,
    useCustomerAppointments,
    useAvailableSlots,
    useCreateAppointment,
    useUpdateAppointment,
    useDeleteAppointment,
    useReportAnnotations,
    useCreateAnnotation,
    useWidgetPreferences,
    useUpdateWidgetPreferences,
    useWidgetData,
    // New module hooks
    usePacpDefects,
    usePacpCategories,
    useCreatePacpDefect,
    useUpdatePacpDefect,
    useDeletePacpDefect,
    useTrainingModules,
    useTrainingModule,
    useSubmitTrainingAttempt,
    useTrainingAttempts,
    useTrainingStats,
    useCreateTrainingModule,
    useUpdateTrainingModule,
    useDeleteTrainingModule,
    useTeamTrainingProgress,
    useTrainingAssignments,
    useAllTrainingAssignments,
    useAssignTrainingModules,
    useTrainingAnalytics,
    useTrainingAssignmentsOverview,
    useUserCertificates,
    useRemindTrainingAssignment,
    useOnboarding,
    useAllOnboarding,
    useCompleteOnboardingStep,
    useReviewTemplates,
    useCreateReviewTemplate,
    useUpdateReviewTemplate,
    useDeleteReviewTemplate,
    useToggleTemplateFavorite,
    useQCReviewStats,
    useKBArticles,
    useKBCategories,
    useCreateKBArticle,
    useUpdateKBArticle,
    useDeleteKBArticle,
    useSurveyResponses,
    useSurveyStats,
    useSubmitSurvey,
    useAdminAnalytics,
    // User (Team Lead) hooks
    useUserDashboard,
    useUserProjects,
    useUserProject,
    useUserTeamMembers,
    useUserTeamMemberDetail,
    useUserTeamMemberDashboard,
    useUserDevices,
    useUserEvents,
    useUserReports,
    useUserNotificationPreferences,
    useUserTeamAnalyticsMetrics,
    useRequestDeleteProject,
    useApproveDeleteProject,
    useRejectDeleteProject,
    useDeleteUserProject,
    useCreateObservation,
    useCreateUserSnapshot,
    useUpdateDeviceAssignment,
    useCreateEvent,
    useUpdateEvent,
    useDeleteEvent,
    useUpdateUserProfile,
    useChangeUserPassword,
    useSaveUserSettings,
    useUpdateUserNotificationPreferences,
    queryKeys,
    // Support (Customer-Rep) hooks
    useSupportAllTickets,
    useSupportGlobalStats,
    useSupportTicket,
    useSupportAssignedTickets,
    useSupportTeam,
    useManagedTeam,
    useSupportCustomerStats,
    useCreateSupportTicket,
    useUpdateSupportTicket,
    useAddTicketResponse,
    useDeleteSupportTicket,
    useAddInternalNote,
    useSupportTags,
    useSupportCustomerHistory,
    useRequestTicketDeletion,
    useReviewTicketDeletion,
    usePendingDeletionRequests,
    // Canned Response hooks
    useCannedResponses,
    useCreateCannedResponse,
    useUpdateCannedResponse,
    useDeleteCannedResponse,
    // Messages / Inbox hooks
    useMessagesInbox,
    useMessagesSent,
    useMessagesThread,
    useMessagesUnreadCount,
    useMessagesContacts,
    useSendMessage,
    useToggleMessageStar,
    useMarkMessageRead,
    useArchiveMessage,
    useDeleteMessage,
    useMarkAllMessagesRead,
    // Operator new module hooks
    useOperatorChecklists,
    useCreateChecklist,
    useToggleChecklistItem,
    useDeleteChecklist,
    useOperatorRouteSites,
    useCompleteRouteSite,
    useOperatorIncidents,
    useCreateIncident,
    useUpdateIncident,
    useOperatorTimeEntries,
    useOperatorTimeSummary,
    useCreateTimeEntry,
    useDeleteTimeEntry,
    useOperatorCachedItems,
    useOperatorPendingSyncs,
    useOperatorOfflineStats,
    useToggleCache,
    useSyncAll,
    // User new module hooks
    useUserWeekSchedule,
    useCreateAssignment,
    useDeleteAssignment,
    useUserBudgets,
    useUserBudget,
    useCreateBudget,
    useAddExpense,
    useUserConversations,
    useUserMessages,
    useSendClientMessage,
    useMarkConversationRead,
    useUserTemplates,
    useCreateTemplate,
    useUpdateTemplate,
    useToggleTemplateStar,
    useDuplicateTemplate,
    useDeleteTemplate,
    useUseTemplate,
    useUserTeamMetrics,
    useUserMemberMetrics,
    useUserTeamSummary,
    useCreatePerformanceMetrics,
    // Overtime
    useUserOvertimeRequests,
    useUserOvertimeSummary,
    useRequestOvertime,
    useWithdrawOvertimeRequest,
    useAdminOvertimeRequests,
    useAdminOvertimeSummary,
    useApproveOvertimeRequest,
    useRejectOvertimeRequest,
    useOvertimeApprovalQueue,
    useRepActivity,
    // Admin — Users, Permissions, Calendar, Projects
    useAllUsers,
    useCustomers,
    useDeleteUser,
    useUpdateUserInfo,
    useSendEmailToUser,
    useAdminChangePassword,
    usePermissionLevels,
    usePermissionModules,
    useCreatePermissionLevel,
    useUpdatePermissionLevel,
    useDeletePermissionLevel,
    useAdminCalendarEvents,
    useCreateCalendarEvent,
    useUpdateCalendarEvent,
    useDeleteCalendarEvent,
    useAdminProjects,
    useProjectHealth,
    useCreateProject,
    // Shared project detail hooks
    useProjectObservations,
    useProjectSnapshots,
    useProjectMetadata,
    usePacpCodes,
    useQCUploads,
};
